HW02 is completed
bon3o/otus-hw pull request #2
Opened 2021-06-23 12:36 UTC by bon3o

## Домашнее задание №2 «Распаковка строки»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я сравнил объем кода с объемом авторского решения. [Зачем сверять объем кода?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D1%81%D0%B2%D0%B5%D1%80%D1%8F%D1%82%D1%8C-%D0%BE%D0%B1%D1%8A%D0%B5%D0%BC-%D0%BA%D0%BE%D0%B4%D0%B0)
  - unpack.go ~45 строк для задания без звездочки
  - unpack.go ~75 строк для задания со звездочкой

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2021-07-01 19:33 UTC, VOOVOOZEL requested changes
Оставил несколько замечаний

2021-07-01 19:33 UTC, VOOVOOZEL commented on hw02_unpack_string/unpack.go
> +	var bstring strings.Builder
можно сформировать блок 
var (
    bstring strings.Builde
    countDigits int
    previousValue rune
    foundControl bool
)

2021-07-01 19:33 UTC, VOOVOOZEL commented on hw02_unpack_string/unpack.go
> +			digit, _ := strconv.Atoi(string(val))
плохая практика игнорировать ошибки

2021-07-01 19:33 UTC, VOOVOOZEL commented on hw02_unpack_string/unpack.go
> +		case val == 92 && foundControl:
лучше использовать константы и избегать магических цифр

2021-07-02 08:54 UTC, bon3o commented on hw02_unpack_string/unpack.go
> +			digit, _ := strconv.Atoi(string(val))
Согласен, но я не могу представить себе ситуацию, когда здесь может возникнуть ошибка. В любом случае, учту.

2021-07-02 17:51 UTC, VOOVOOZEL approved these changes
Одобрено 10/10

2021-07-06 08:32 UTC, bon3o commented
> Одобрено 10/10

Не могу вмерджить

2021-07-15 12:05 UTC, VOOVOOZEL approved these changes
ok

2021-07-15 12:06 UTC, VOOVOOZEL approved these changes

2021-07-15 12:43 UTC, merged